### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by Shuazijun** [AonaSuzutsuki/SavannahManager#3]
![图片](https://user-images.githubusercontent.com/30001049/80871123-6ba72a80-8cdd-11ea-96e3-447d75c835b0.png)
How to add language files correctly and display them?

**Comment by AonaSuzutsuki** [comment]
the language has not automatically added to the menu.
therefore, you need to create and compile the XAML file and language files to add it.
i didn't predicted adding it to the new one.

# Lanugage Files
1. copy the resx file in English or Japanese
 \* add the language code to the end. (exp: Resource.es-ES.resx)
2. edit the resx file you copied

# ResourceService
1. add a language code same as "Lanugage Files" to "#region Static Members".
```cs
public const string Spanish = "es-ES";
```

# View & ViewModel
1. add elements to MainWindow.xaml in the same way as in English and Japanese.
 \* command can be changed to your likinga
2. add command and method to "MainWindowViewModel".
3. pass "ResourceService.{LanguageName}" to "model.ChangeCulture" and run it
```cs
model.ChangeCulture(ResourceService.Spanish);
model.RefreshLabels();
```
