### ISSUE TITLE
Make English language the default language 

### ISSUE THREAD

**Issue by BoQsc** [AonaSuzutsuki/SavannahManager#8]
![image](https://user-images.githubusercontent.com/21064622/124269713-ec60f100-db43-11eb-9ae4-b61a061f0651.png)

**Comment by AonaSuzutsuki** [comment]
I'm currently thinking about countermeasures.
It will be supported in the next update.

**Comment by BoQsc** [comment]
> I'm currently thinking about countermeasures.
> It will be supported in the next update.

Thank you.

**Comment by AonaSuzutsuki** [comment]
fixed and released by v2.4.42.3.
delete the settings.ini file if it is not in English at startup.
